export const ADD_COMMENT = "ADD_COMMENT";

export const DISH_LODDING = "DISH_LOADING";
export const DISH_FAILD = "DISH_FAILD";
export const DISH_ADD = "ADD_DISH";

export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";

export const PROMOS_LOADING = "PROMOS_LOADING";
export const ADD_PROMOS = "ADD_PROMOS";
export const PROMOS_FAILED = "PROMOS_FAILED";

export const LEADERS_LOADING = "LEADERS_LOADING";
export const ADD_LEADERS = "ADD_LEADERS";
export const LEADERS_FAILED = "LEADERS_FAILED";

export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const FEEDBACK_FAILED = "FEEDBACK_FAILED";
